### ISSUE TITLE
Fix/Todo List

### ISSUE THREAD

**Issue by 0xdeafcafe** [branch-app/branch#46]
**Must do**
- [x] Flash Messages
- [x] Blog
- [x] About
- [x] Halo 4 home page
- [x] Halo 4 Playlist Page
- [x] Halo 4 Challenge Page
- [x] Message on Game History on Service Record when no games have been played
- [x] Gamertag Replacements
- [x] body.home .games .game .mask .container p - set this font to fall back to Arial. (jesus open-sans looked shit)

**Maybe**
- [x] Make Service Record Row Keys lowercase?
